// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVsjkicttPQsRyD-WVaV3nKR-HmFgEPbk',
    appId: '1:781188748949:web:782855fb18be9a3f91ad9c',
    messagingSenderId: '781188748949',
    projectId: 'auth-fhome',
    authDomain: 'auth-fhome.firebaseapp.com',
    storageBucket: 'auth-fhome.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPTRewMulPfN3ew5V64b9W5zj0_4FHTS8',
    appId: '1:781188748949:android:b2f60b56feb0f07191ad9c',
    messagingSenderId: '781188748949',
    projectId: 'auth-fhome',
    storageBucket: 'auth-fhome.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5XhGRG4w3o-XPip-X-hFRsiY3x2yZegg',
    appId: '1:781188748949:ios:0726a98d036a50d091ad9c',
    messagingSenderId: '781188748949',
    projectId: 'auth-fhome',
    storageBucket: 'auth-fhome.appspot.com',
    iosClientId: '781188748949-5j5tfg3umv15me87fq19khi3haargsm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fHomeMo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5XhGRG4w3o-XPip-X-hFRsiY3x2yZegg',
    appId: '1:781188748949:ios:0726a98d036a50d091ad9c',
    messagingSenderId: '781188748949',
    projectId: 'auth-fhome',
    storageBucket: 'auth-fhome.appspot.com',
    iosClientId: '781188748949-5j5tfg3umv15me87fq19khi3haargsm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fHomeMo',
  );
}
